制限モードの追加
geolonia/embed pull request #255
Opened 2021-10-27 09:03 UTC by kamataryo

402 が tileserverless から帰ってきたときに制限モードが表示されるようになります。
制限モードではそれを示すダイアログが表示され、高ズームにしても低ズームの地図 (oceanus、water) だけが表示され続けます。

~~制限モードの挙動は `map.geoloniaConfig.restrictedMode` で設定できます。~~

実際に制限されている様子:
http://geolonia-mapkey-limit-test.kamataryo.com/#0/0/0

<img width="720" alt="スクリーンショット 2021-10-27 17 57 59" src="https://user-images.githubusercontent.com/6292312/139034746-3e4bde0e-f0b7-46d9-8e27-64d802fa1991.png">

2021-11-01 07:13 UTC, kamataryo commented on docs/limitation-test.html
> +    map2.geoloniaConfig = {
ラベルをカスタマイズするための設定を挿し込む API を考えているんですけどこのような方法はどうでしょう？
https://deploy-preview-255--geolonia-embed.netlify.app/limitation-test.html#0/0

<img width="928" alt="スクリーンショット 2021-11-01 16 12 17" src="https://user-images.githubusercontent.com/6292312/139634988-a54b66bf-0ce3-4282-8cfc-b354e9bf8eb0.png">
/0

2021-11-01 07:53 UTC, keichan34 commented on docs/limitation-test.html
> +    map2.geoloniaConfig = {
いいと思います。。 data- に出すと設定しやすいと思うけど、 data を使いすぎると後からの管理が大変になりますよね。。こういう形でいいかなと思います。ちょっと確認します

2021-11-01 07:58 UTC, kamataryo commented on docs/limitation-test.html
> +    map2.geoloniaConfig = {
@keichan34 ありがとうございます。`data-`とはちょっと性質が違うかなと思って分けました。地図表示とは関係ない設定はこっちに詰めこむイメージでいます。

2021-11-09 01:22 UTC, keichan34 commented on docs/limitation-test.html
> +    map2.geoloniaConfig = {
JSで設定するようにしましょう！

2021-11-10 09:38 UTC, kamataryo commented on docs/limitation-test.html
> +        debug: true,
@keichan34 デバッグモードを追加しました。

2021-11-11 04:26 UTC, miya0001 commented
これ申し訳ないのですが、制限モードそのものと、表示内容をカスタマイズする機能はわけてもらってもいいですか？
正直このカスタマイズ機能は複雑すぎるなと思いました。

2021-11-11 04:58 UTC, kamataryo commented
@miya0001 @keichan34 制限モードのカスタマイズの部分を除外しました。

2021-11-11 07:57 UTC, keichan34 approved these changes

2021-11-11 13:17 UTC, miya0001 requested changes
デザインチームにデザインを考えてもらいましょう。

2021-11-17 08:18 UTC, kamataryo commented
#262 の後に対応

2021-11-18 05:24 UTC, kamataryo commented
画像の表示に差し替えました。
以下でデモを表示できます。
http://geolonia-mapkey-limit-test.kamataryo.com

![screencapture-geolonia-mapkey-limit-test-kamataryo-2021-11-18-14_15_14](https://user-images.githubusercontent.com/6292312/142356951-ebed2776-665c-43fe-91ec-2459cc2e6304.png)

2021-11-18 05:50 UTC, naogify approved these changes

2021-11-18 06:06 UTC, miya0001 approved these changes

2021-11-19 00:13 UTC, kamataryo commented
NOTE:
マージ後、メインブランチは v2.0.0-pre.3 としてリリース。
制限モードのコミットは、 v1.18.1 に取り込んで v1.19.0 およびとしてリリース。

2021-11-19 01:19 UTC, kamataryo commented
こちらマージします。

2021-11-19 01:19 UTC, merged