Set Geojson as URL for simpleStyle class
geolonia/embed pull request #283
Opened 2022-04-27 03:20 UTC by naogify

2022-04-27 05:50 UTC, naogify commented
メモ：後は、実際にビルドした Embed API に geojson url を渡してテストして見る

2022-04-27 22:57 UTC, keichan34 requested changes
確認よろしくおねがいします

2022-04-27 22:57 UTC, keichan34 commented on src/lib/simplestyle.js
> +          console.error(error); // eslint-disable-line no-console
console.errorを残すならもっと説明してください `console.error('Failed to load GeoJSON:', error)`

2022-04-27 22:57 UTC, keichan34 commented on src/lib/simplestyle.js
> +    this.setGeoJSON(geojson);
ここで this.geojson を設定しているので、52行の `this.geojson = geojson` が不要になるはず

2022-04-27 22:57 UTC, keichan34 commented on src/lib/simplestyle.js
> +            this.fitBounds();
ここでリセットした方がいいと思います。

現状、おそらくこうなります

`ss = new SimpleStyle(...).fitBounds()` -> 思ったとおりに動く
`ss.updateData(URL)` -> fitBoundsをコールしなくても this.callFitBoundsがまだtrueなので、ここのthis.fitBoundsが走らせられる

2022-04-27 23:34 UTC, naogify commented
@keichan34 
ありがとうございます。上の3点修正しました。またお手すきの時に確認いただけますと！

2022-04-27 23:38 UTC, kamataryo commented on src/lib/simplestyle.js
> +      this._loadingPromise = fetchGeoJSON();
非同期の制御、`this.map.fire('simplestyle.load')` などとコールしてカスタムイベントにするのはどう思いますか？

2022-04-27 23:38 UTC, kamataryo commented on src/lib/simplestyle.test.js
> +    const { default: simpleStyle } = await import('./simplestyle');
ここで Dynamic Import している理由って何かありますか？

2022-04-27 23:47 UTC, naogify commented on src/lib/simplestyle.test.js
> +    const { default: simpleStyle } = await import('./simplestyle');
@kamataryo 
あ、他のテストの書き方に合わせてそうしました。確かにファイルの先頭で通常の import でも良さそうですね!（ちなみに前のテストが Dynamic Import になっている理由があれば教えてもらえると嬉しいです!）

2022-04-27 23:59 UTC, kamataryo commented on src/lib/simplestyle.test.js
> +    const { default: simpleStyle } = await import('./simplestyle');
なるほど。了解です。どっちでも大丈夫だと思います。

2022-04-28 00:04 UTC, naogify commented on src/lib/simplestyle.js
> +      this._loadingPromise = fetchGeoJSON();
@kamataryo 

fetchedJSON() の中（348行目？）で、`this.map.fire('simplestyle.load')` を追加して、

テストの中で、`this._loadingPromise = fetchGeoJSON();` の代わりに、下の様に書くイメージでしょうか？

```
map.on('simplestyle.load', () => {
    assert.deepEqual(true, map.bounds);
}
```

そうすれば、今後簡単にイベントを取得できる様になるから良さそうですね。

2022-04-28 00:04 UTC, kamataryo commented on src/lib/simplestyle.test.js
> +    const { default: simpleStyle } = await import('./simplestyle');
強いていうならテスト環境がブラウザ環境を模しているので、 `window.simpleStyle` から使うから static import はちょっと違う気がするし、そもそも `require` はナシって感じでしょうか。

2022-04-28 00:10 UTC, kamataryo commented on src/lib/simplestyle.js
> +      this._loadingPromise = fetchGeoJSON();
はい。 `_loadingPromise` のメンバーをクラスに追加しないで済むようににしたいと思ってます。
@keichan34 イベント発火させるのどう思われますか？

コールバックになるのでテストはこうかな？

```javascript
it('should load GeoJSON from url', (done) => {
  // ...
  map.on('simplestyle.load', () => {
    assert.deepEqual(true, map.bounds);
    done()
  }
}
```

2022-04-28 00:14 UTC, naogify commented on src/lib/simplestyle.test.js
> +    const { default: simpleStyle } = await import('./simplestyle');
なるほど! それであれば下の様な書き方の方が良いでしょうか、

@kamataryo 
了解です! 問題ない様であればこのままにしようかと思います。

余談ですが、ブラウザを模すのであれば下の様な書き方の方がベターでしょうか？でもグローバル変数に入れるとどこで書き変わるか分からないのでテストのときは避けた方が良いのか、、🤔
```
import simpleStyle from './simplestyle';
window.simpleStyle = simpleStyle;
```

2022-04-28 00:19 UTC, kamataryo commented on src/lib/simplestyle.test.js
> +    const { default: simpleStyle } = await import('./simplestyle');
そうですね..
ただ、現状そこまで複雑なモジュールをテストしているわけではない（他のモジュールと一緒に window のメンバーに相互に依存していたりするわけではない）ので、読みやすいと思うもので大丈夫だと思います。このままでも全然 OK です。

2022-04-28 00:45 UTC, naogify commented on src/lib/simplestyle.test.js
> +    const { default: simpleStyle } = await import('./simplestyle');
@kamataryo 

>（他のモジュールと一緒に window のプロパティになって相互に依存していたりするわけではない）

なるほどこのケースでは必要になるって事ですね。ありがとうございます!

2022-04-28 01:22 UTC, kamataryo commented on src/lib/simplestyle.js
> +      this._loadingPromise = fetchGeoJSON();
こちら、すでに議論色々ありましたね。蒸し返してすみません。
イベントエミッターの追加は改善の議論として別途進めていきましょう。

2022-04-28 02:24 UTC, naogify commented on src/lib/simplestyle.js
> +      this._loadingPromise = fetchGeoJSON();
@kamataryo
了解です！別issue として後で立てます。

@keichan34 @kamataryo 
もし問題ないようでしたら、お手すきの時に Approve お願いできますと！

2022-04-28 04:06 UTC, miya0001 requested changes
https://github.com/geolonia/embed/blob/master/src/lib/geolonia-map.js#L215

上のあたりに対する修正も必要なはず。

2022-04-28 04:20 UTC, naogify commented
@miya0001 了解です！後で確認してみます。

2022-05-09 02:55 UTC, naogify commented
> https://github.com/geolonia/embed/blob/master/src/lib/geolonia-map.js#L215
> 
> 上のあたりに対する修正も必要なはず。

@miya0001 @keichan34 

GeoJSON を フェッチする機能を SimpleStyle Class に実装したので、元々 Embed API でフェッチしていた箇所を削除しました。確認お願いします!

https://github.com/geolonia/embed/blob/ebfcc6f4c8a25ec214a64195de5aa809ce4c7796/src/lib/geolonia-map.js#L209-L216

2022-05-09 04:19 UTC, keichan34 approved these changes

2022-05-10 02:22 UTC, miya0001 approved these changes

2022-05-10 02:23 UTC, merged