Fix simple style cases
geolonia/embed pull request #305
Opened 2022-09-30 03:43 UTC by kamataryo

2022-09-30 03:57 UTC, keichan34 requested changes
Mapboxの方で確認すると正確には simplestyle か Simplestyle かもしれないけどもうgeoloniaでは simpleStyle や SimpleStyle のcamel-caseになってしまっているからあえて変えなくてもいいかなと思います。。

2022-09-30 04:04 UTC, kamataryo commented
@keichan34 なるほど..、 `SimpleStyle` で公開すること（このプルリクエスト自体）についてはどう思いますか？

2022-09-30 09:50 UTC, kamataryo commented
@keichan34 `SimpleStyle` としました

2022-10-03 03:47 UTC, keichan34 approved these changes
ありがとうございました！

2022-10-03 05:21 UTC, naogify approved these changes

2022-10-03 05:22 UTC, merged