Attribution ShadowDOM
geolonia/embed pull request #306
Opened 2022-09-30 08:41 UTC by naogify

Attribution Controlが外部のCSSの影響を受けてしまうので、 Attribution Controlのみを ShadowDOMとして追加しました。

2022-09-30 09:24 UTC, naogify commented
@keichan34 
地図を動かした時にアトリビューションを閉じる CSS も追加されていました、、。こちらレビューを少し待って頂ければと!

2022-09-30 09:35 UTC, naogify commented
@keichan34 
こちらの CSS の件、修正しました!

2022-10-04 03:32 UTC, naogify commented
@keichan34 
こちら `©` で改行しないように、css を追加しました。確認お願いします!

プレビュー
https://deploy-preview-306--geolonia-embed.netlify.app/debug.html

<img width="492" alt="スクリーンショット 2022-10-04 12 22 01" src="https://user-images.githubusercontent.com/8760841/193727616-a54bac72-984c-4787-bb8d-e2b65693853f.png">

2022-10-04 04:37 UTC, keichan34 requested changes
細かい修正ですがよろしくお願いします。
あと、テスト用のファイルを削除お願いします。(debug.html, style-long-attrb.json）

2022-10-04 04:37 UTC, keichan34 commented on src/lib/util.js
> +/**
maplibreから抽出したutilを別ファイルに分けましょう。`maplibre-util.js` とかかな。
もし将来このライブラリをTSに移行したら、簡単に元ソースを参照して使えるようにしたい

2022-10-04 04:37 UTC, keichan34 commented on src/lib/CustomAttributionControl.js
> +    .mapboxgl-ctrl, .maplibregl-ctrl {
ここでは `.mapbox-*` 系の互換性のためのセレクタは不要です（shadow DOM内では完全にコントロールされているという環境なので、他のユーザーがこの中に何かしら入れたりすることはないし、外から触れることも無いので）

2022-10-04 04:40 UTC, keichan34 commented
あ、ごめんなさい。©とその後の文言が改行しないようにCSSを指定したところをみせてもらってもいいですか？（なんか差分に埋もれてしまったような気がします。。。）（そして、debug.htmlのサンプルだとリンクになっていないので本番環境とは若干違うと思います。。

2022-10-04 07:01 UTC, naogify commented
@keichan34 
ありがとうございます! 上で指定して頂いた点を修正しました。 （後で、debug.html , style-long-attrb.json は削除します）
https://deploy-preview-306--geolonia-embed.netlify.app/debug.html


> あ、ごめんなさい。©とその後の文言が改行しないようにCSSを指定したところをみせてもらってもいいですか？

こちらの件ですが下のように指定しています。（`overflow-wrap: nowrap` を指定したのですが、©️の直後に改行されてしまったので、 [*1](https://developer.mozilla.org/ja/docs/Web/CSS/overflow-wrap#:~:text=%E3%83%A1%E3%83%A2%3A%20word%2Dbreak%20%E3%81%A8%E3%81%AF%E5%AF%BE%E7%85%A7%E7%9A%84%E3%81%AB%E3%80%81%20overflow%2Dwrap%20%E3%81%AF%E5%8D%98%E8%AA%9E%E5%85%A8%E4%BD%93%E3%81%8C%E3%81%82%E3%81%B5%E3%82%8C%E3%81%9A%E3%81%AB%E8%A1%8C%E5%86%85%E3%81%AB%E9%85%8D%E7%BD%AE%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%84%E5%A0%B4%E5%90%88%E3%81%AB%E3%81%AE%E3%81%BF%E3%80%81%E6%94%B9%E8%A1%8C%E3%82%92%E7%94%9F%E6%88%90%E3%81%97%E3%81%BE%E3%81%99%E3%80%82)  `word-break` を使用しました。）

https://github.com/geolonia/embed/blob/e692a52ce26317069d31783417fe9a7887f75543/src/lib/CustomAttributionControl.js#L174

2022-10-04 07:12 UTC, keichan34 commented
なるほど。すごい細かいのですが、その実装だとこういうことが起こりうるんですね。この場合は「OpenStreetMap」などの一つの文言は分けたくないなと思って、 break-all が不適切かなと思います。

![Screenshot from 2022-10-04 16-09-55](https://user-images.githubusercontent.com/1064513/193756872-38b8fb5c-f872-4063-9c3f-138cddd2e206.png)

変わりに、それぞれのattributionを別のspanに入れて、そのspan自体がブレークしないようにできないかな。display: inline-block とか？

2022-10-04 07:27 UTC, keichan34 commented
なるほど。これでいいですね。ありがとうございました！

2022-10-05 02:01 UTC, keichan34 reviewed
ありがとうございます！

2022-10-05 02:01 UTC, keichan34 approved these changes
おっと、アプルーブするの忘れた。ありがとうございました！

2022-10-05 02:02 UTC, merged