Miscellaneous refactorings
geolonia/embed pull request #372
Opened 2023-07-24 05:52 UTC by phanect

リファクタリングをいくつか行いました。

- star import を解消し treeshaking が動作するように修正
- embed.ts の処理のうち副作用が発生する部分を関数に分離
- 内部から `window.geolonia` へのアクセスをやめる
- `window.geolonia._stage` や `window.geolonia._apiKey` への代入によってステージや API キーを指定する方法のサポートを削除
- API キーのパースに失敗した際に自動的に `YOUR-API-KEY` を API キーとみなすのをやめる
- 型付けを強化
- バージョン番号を package.json からではなく、version.ts を生成してそちらから呼び出すように修正

など

2023-07-24 05:54 UTC, phanect commented
CI エラーが出たため一旦 Draft にします

2023-07-24 09:43 UTC, phanect commented
CI エラー解消しました。

2023-07-25 01:22 UTC, kamataryo commented on .npmignore
> +src
個人的には npm install された時に dist と一緒に src も含まれている方が好みです。大したサイズではないと思うので..
これは単なるコメントで、どっちでも良いと思うので、対応はお任せします。

2023-07-25 01:22 UTC, sugama-satsuki approved these changes

2023-07-25 01:23 UTC, phanect commented on .npmignore
> +src
了解しました。
私はそんなにこだわりはないので、src は含まれるようにしておきます。

2023-07-25 01:24 UTC, kamataryo commented on src/lib/geolonia-map.ts
> +    const container = getContainer(params) as Container | false;
ここって、型推論効きませんでしたか？

2023-07-25 01:32 UTC, phanect commented on src/lib/geolonia-map.ts
> +    const container = getContainer(params) as Container | false;
getContainer() は HTMLElement を返すようになっているのですが、container 変数が HTMLElement のままだと、後で container.geoloniaMap という標準外のプロパティを生やす時に型エラーが出ます。
型エラーを回避するために、別途 Container という HTMLElement を拡張した型を作って、それに変換しています。

いずれ geoloniaMap プロパティを生やさない実装へのリファクタリングが必要だと思いますが、今回は型定義をいじることでお茶を濁してます。

2023-07-25 01:35 UTC, kamataryo commented on src/lib/geolonia-map.ts
> +    const container = getContainer(params) as Container | false;
あ、なるほど、そういえばコンテナの HTMLElement オブジェクトに Map の参照をくっつけてましたね.. この仕様忘れてました。
理解できました。ありがとうございます。

2023-07-25 02:31 UTC, kamataryo requested changes

2023-07-25 02:31 UTC, kamataryo commented on .npmignore
> +src
```suggestion
```

2023-07-25 02:31 UTC, kamataryo commented on .npmignore
> +src
@phanect あ、この行ですが、消す方針で良かったでしょうか？

2023-07-25 02:32 UTC, phanect commented on .npmignore
> +src
あ、はい、消す方向です。
ありがとうございます。

2023-07-25 02:36 UTC, kamataryo approved these changes
ありがとうございました！

2023-07-25 02:37 UTC, merged