WebGL 2.0 がサポートされているかチェックする
geolonia/embed pull request #390
Opened 2024-04-23 08:36 UTC by naogify

2024-04-23 10:23 UTC, sugama-satsuki approved these changes

2024-04-24 00:19 UTC, keichan34 requested changes
手法をちょっと変更したいです、、。
今は新しい webgl2 コンテキストを新しく作ろうとしているけど、この手法ではいくつかの問題があるのかなと思います:
* 余計にコンテキストを作ってしまう（例えば Chrome は16個まで、古い順から削除される)
* これが通ったといっても地図が表示されるか、というのも完全にわかるわけではない。。

ので、理想的な実装は、地図を初期化しようとするけど、何かしらの問題で失敗した時にエラーを表示する。例えば、コンテキストが起動できなくて `new maplibregl.Map(...)` で例外が発火されたら、それをキャッチしてユーザーにわかりやすい表示にする。

今回、alertで出してるけど、alertだと複数地図ある時にスパムっぽくなるし、場合によって地図がメインじゃないサイトに邪魔になる可能性にもなるので、地図があるはずの場所にHTMLで表示してください。

イメージとしてはGoogleMapsのエラーメッセージ（リクエスト上限足したらエラー画面が出るような設定はembed APIでも入っているはず、、）の方が親切だと思います。
<img width="457" alt="Screenshot 2024-04-24 at 9 18 35" src="https://github.com/geolonia/embed/assets/1064513/30bc8d38-0097-4dda-a555-95aaa15dc565">

2024-05-10 06:46 UTC, naogify commented
以下のように地図表示エリアに警告を表示するようにしました。

![スクリーンショット 2024-05-10 15 44 35](https://github.com/geolonia/embed/assets/8760841/13d89991-8412-4d53-ab9c-fb46ba1654e4)

![スクリーンショット 2024-05-10 15 43 53](https://github.com/geolonia/embed/assets/8760841/a7788114-9cc5-4a73-b402-58a9a29b5f96)

## 確認方法

- https://geolonia.esa.io/posts/1856
- https://geolonia.esa.io/posts/1851

2024-06-05 07:57 UTC, keichan34 requested changes
細かいですがre-throwしていないところのコメントよろしくお願いします :bow:

2024-06-05 07:57 UTC, keichan34 commented on src/lib/render.ts
> +          console.error('[Geolonia] Failed to initialize map', e); // eslint-disable-line
ここに、なんでre-throwをしていないかをコメントなどで説明してください

2024-06-20 07:35 UTC, naogify commented on src/lib/render.ts
> +          console.error('[Geolonia] Failed to initialize map', e); // eslint-disable-line
@keichan34 
遅くなりましたが、以下のようにコメントを追加しました。お手隙の際に確認お願いしても良いでしょうか？
`Not throw error because, following maps will not be rendered.`

2024-06-20 07:36 UTC, keichan34 approved these changes

2024-06-24 00:22 UTC, merged