loadImage の後方互換性のための処理を追加
geolonia/embed pull request #397
Opened 2024-07-30 02:22 UTC by naogify

MapLibre GL JS v4.4.1 の から、loadImage の呼び出し方が以下のように変更になりましたが、後方互換性を保つための処理を追加しました。

```
  // v4.4.1 以降
  map.loadImage(url)

  // v4.4.1 以前
  map.loadImage(url, callback)
```

Related to https://github.com/maplibre/maplibre-gl-js/pull/3422/

2024-09-30 06:18 UTC, keichan34 commented on src/lib/geolonia-map.ts
> +   *  Backward compatibility for breaking change of loadImage() in MapLibre GL JS v4.4.1.
4.0.0 から breaking change です

2024-09-30 08:44 UTC, naogify commented on src/lib/geolonia-map.ts
> +   *  Backward compatibility for breaking change of loadImage() in MapLibre GL JS v4.4.1.
@keichan34 ありがとうございます! 修正しました。

2024-09-30 09:22 UTC, keichan34 requested changes

2024-09-30 09:22 UTC, keichan34 commented on src/lib/util.ts
> +): Promise<void> => {
ここasync使っているのはおそらく awaitシンタックスだけのためだけど、ここは promise からcallbackに変更するだけのものなので、

```
(promise: Promise<...>, callback) => {
  promise.then((response) => callback(null, ...)).catch(callback)
```
みたいな書き方だとわかりやすいと思います（この関数から返しているpromiseは特に使われることが無いので冗長です、、）

ちなみに、これは複数の場所を使うとすると、汎用的な関数にしたほうがいいかも:

```
function promiseToCallback<T>(promise: Promise<T>, callback: (error: unknown, data: T) => void) {
```

[playground](https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABABwE5wLYwM4FMAqcAwgIYA2ZARiRANYA8+AfABRqY64BciACuljyMmAGkQRyVGrR4tcqdKh7haYOAHcwYgCYkoJAPw98ASkQBeJogBucGNrMBvAFCI3KAZwB0UABa4wFhZdfTNLcUlqOhYwEAodPRITEy8JKAhfFgkKKNoTZwBfZ2cIBGwoDw48C0QwXHU+TyFy1BgwAHNWFlRcbDgya1wwqxd3RDwofBgMXDgQKCDhxB6+gdwWAHJtBFwNkzEAVgAGI-yC-Od2QQJiSOk2JtwxOQUE0IsR13cYYEQWKAAnshZr8QiQLOZzIgNuBtLhgG1cNo9stcFAQKgwABuL5uUpgVa4LxkODtYKJM4mIA)

2024-10-01 05:05 UTC, naogify commented on src/lib/util.ts
> +): Promise<void> => {
@keichan34 
ありがとうございます! 

> この関数から返しているpromiseは特に使われることが無いので冗長です、、

テストの時に promsie があると実行結果を待ってテストできるので便利なのと、`eslint-disable-next-line promise/prefer-await-to-then` を使う必要が出てくるので、promise を返したいと思ったのですがどうでしょうか？

```
await loadImageCompatibility(promise, callback);
assert.deepEqual(callback.firstCall.args[1], mockResponse.data);
```

2024-10-01 05:58 UTC, keichan34 commented on src/lib/util.ts
> +): Promise<void> => {
まずは eslint は今回ignoreしてもいいと思います（promise移行のためのものだし、承知したうえで利用しているので例外を作ってもいい）

ただ、テストで使っているのか、、

どちらかというとcallbackをテストしたい時はpromiseとあまり混ざらないほうがいいと思うので、test自体もcallbackにした方がいいと思います。今回は関係無いけど、厳密にいうと返却に入っているpromiseとcallbackが一緒のものではないので、promiseが終わったからと言ってもcallbackがコールされているかは別のものです、、。

一般的なcallbackテストは

```javascript
test('..', (t, done) => {
  loadImageCompatibility(promise, (err, data) => {
    assert.deepEqual(data, mockResponse.data);
    done();
  });
});
```

この方は、 firstCall とかを使わずに、実際使われるような表記でテストできるので、より良いテストが書けるかと思います。

2024-10-28 01:03 UTC, keichan34 commented
@naogify 勝手に修正しました
汎用的な promiseToCallback の関数（ nodejs でいうと [callbackify](https://nodejs.org/api/util.html#utilcallbackifyoriginal) みたいな感じ）を最初作ろうと思ったんですが、 loadImage のcallbackの形は (error, data, expiry) の一般的ではない形だったので、やっぱりカスタム対応が必要でした。その旨を、念の為コメントに追記しました。

2024-10-28 01:04 UTC, merged

2024-10-28 01:05 UTC, naogify commented
@keichan34 
すみません! 手つけれてなかったです。ありがとうございます🙏